name: Deploy React to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Check for changes in frontend directory
      id: check_changes
      run: |
        git diff --exit-code HEAD^ HEAD -- frontend
      continue-on-error: true  # Continue if there are no changes

    - name: Install dependencies
      if: steps.check_changes.outcome == 'success'
      run: |
        cd frontend
        npm install

    - name: Build the frontend
      if: steps.check_changes.outcome == 'success'
      run: |
        cd frontend
        npm run build

    - name: Configure AWS credentials
      if: steps.check_changes.outcome == 'success'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync to S3
      if: steps.check_changes.outcome == 'success'
      run: |
        aws s3 sync frontend/build s3://$S3_BUCKET_NAME --delete
      env:
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
